server:
  port: 8080

management:
  security:
    enabled: false

spring: 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SeungHwan-Lee/SpringBoot-Config-repository.git
#          username: 
#          password:
  rabbitmq:
    host: 192.168.85.128
    username: testuser
    password: testuser
    