server:
  port: 8080

spring: 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SeungHwan-Lee/SpringBoot-Config-repository.git
          username: 
          password: 